language: python
python:
- '3.6'
cache:
  directories:
  - $HOME/.cache/pip
  - .arca/cache
install:
- python -m pip install --upgrade pip pipenv
- pipenv install --deploy --dev
script:
- pipenv graph
- pipenv run test
after_script:
- echo "Suplementary logs:"
- cat .arca/naucse.log
